[package]
name = "hoshi-reader"
version = "1.1.1"
description = "Japanese EPUB reader for macOS and Windows"
authors = ["Manhhao"]
license = "GPL-3.0-or-later"
repository = "https://github.com/Manhhao/Hoshi-Reader-Desktop"
edition = "2024"
rust-version = "1.88"

[lib]
name = "hoshi_reader_lib"

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }
serde_json = "1.0"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.11.2", features = [] }
rbook = "0.7"
urlencoding = "2.1.3"
tauri-plugin-dialog = "2.7.1"
tauri-plugin-window-state = "2"
uuid = { version = "1.23.2", features = ["v4"] }
regex = "1.12.3"
unicode-segmentation = "1.13.2"
reqwest = { version = "0.13", default-features = false, features = ["json", "form", "query", "native-tls"] }
base64 = "0.23"
sha1 = "0.11"
rusqlite = { version = "0.40", features = ["bundled"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
open = "5.4.0"
sha2 = "0.11.0"
keyring-core = "1"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
hoshidicts = { git = "https://github.com/Manhhao/hoshidicts-rs.git", branch = "main" }
mp3lame-encoder = "0.2.4"
unicode-normalization = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tokio = { version = "1", features = ["sync", "time", "macros"] }
tokio-util = "0.7"
tauri-plugin-updater = { version = "2", default-features = false, features = ["native-tls", "zip"] }
opus = "0.4"
ogg = "0.9"
rubato = "5"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
apple-native-keyring-store = { version = "1", features = ["keychain"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
windows = { version = "0.61", features = [
    "Media",
    "Storage_Streams",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_System_WinRT",
    "Win32_UI_Shell",
] }
windows-native-keyring-store = "1"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1

[profile.release.build-override]
strip = "none"
